internal/cmd/validate.go
pkg/utils/types.go
pkg/validate/validate.go
pkg/validators/validate_current_csv.go
pkg/validators/validator_addon_label.go
pkg/validators/validator_default_channel.go

Signed-off-by: Yashvardhan Kukreja <ykukreja@redhat.com>
Ref: https://github.com/mt-sre/addon-metadata-operator/pull/15#discussion_r741731475

Shift: from pointer semantics to value semantics while passing MetaBundle objects

---

internal/testutils/testutils.go
pkg/utils/bundle_utils_test.go
pkg/utils/default_bundle_parser.go

Fixes: https://issues.redhat.com/browse/MTSRE-360
Signed-off-by: ashish <asnaraya@redhat.com>

return early with an error if manifests directory doesnt exist

---

go.mod
go.sum
pkg/validators/am0005_test_harness.go
pkg/validators/test_am0005.go

Adds a new validator for ensuring the presence of test-harness image in the addon's metadata file.

Test harness validator

---

pkg/validators/am0008_namespace.go
pkg/validators/test_am0008.go

Signed-off-by: ashish <asnaraya@redhat.com>

add addon namespace validations

---

pkg/validators/am0006_dms_snitchnamepostfix.go
pkg/validators/helpers.go
pkg/validators/test_am0006.go

Signed-off-by: Yashvardhan Kukreja <ykukreja@redhat.com>

MTSRE-373 | add: dms snitchNamePostFix validator

---

pkg/validators/am0009_addon_parameters.go
pkg/validators/test_am0009.go

Signed-off-by: Yashvardhan Kukreja <ykukreja@redhat.com>

MTSRE-348 | Add: addon metadata addOnParameters validator

---

go.mod
pkg/validators/am0007_csv_install_modes.go
pkg/validators/registry.go
pkg/validators/test_am0007.go

To be merged after #34  and #35

Add 007_csv_install_modes validator

---

internal/testutils/reference_addon.go
internal/testutils/testutils.go
pkg/types/validators.go
pkg/utils/meta_loader_test.go
pkg/validate/validate_test.go
pkg/validators/am0001_test.go
pkg/validators/am0002_test.go
pkg/validators/am0004_test.go
pkg/validators/am0005_test.go
pkg/validators/am0006_test.go
pkg/validators/am0007_test.go
pkg/validators/am0008_test.go
pkg/validators/am0009_test.go
pkg/validators/registry.go
pkg/validators/validators_test.go

- Moves validators testing to external test package.
- Add error handling to ValidatorTest interface
- Removed dangerous log.Fatal calls

[MTSRE-399] Review validators testing framework.

---

internal/cmd/validate.go

This PR writes user-friendly messages to `stdout` rather than `stderr` when using the `validate` sub-command. This change is required because output redirection does not work correctly when `mtcli` is run from CI.

[MTSRE-409] - Write fatal validation setup errors to stdout

---

config/crd/bases/addons.managed.openshift.io_addonimagesets.yaml
config/crd/bases/addons.managed.openshift.io_addonmetadata.yaml
pkg/ocm/v1/addons.go
pkg/ocm/v1/zz_generated.deepcopy.go
pkg/validators/am0009_addon_parameters.go

Also modify AM0009 to use the new user provided error message.

[MTSRE-405] Add validation_err_msg to AddOnParameters schema.

---

.goreleaser.yml

Fixes CI issues when cleaning up dist folder before new builds.

Ensure `dist` is not written back to host volume

---

.goreleaser.yml

Enhancements to the `.goreleaser.yml` file which does the following:
- Eliminates duplicated archives caused by an superfluous list item
- Reduces duplication with YAML anchors
- Removes dead code for `*386` builds
- Renames builds to reflect compiler rather than target
- Makes the changelog compatible with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

ci: goreleaser config enhancements

---

.dockerignore
Dockerfile.build
magefile.go

fix: updating AMO build image to use go1.17

---

README.md

Added `Adding validators` reference in the doc.

nit fixes to doc: added "Adding validators" reference

---

go.mod
internal/testdata/validators/am0003/csv_name_invalid.yaml
internal/testdata/validators/am0003/csv_replaces_invalid.yaml
internal/testdata/validators/am0003/csv_semver_invalid.yaml
internal/testdata/validators/am0003/csv_valid.yaml
pkg/validator/am0003/operator_name.go
pkg/validator/am0003/operator_name_test.go
pkg/validator/register/register.go

Refactoring Sam's PR for `AM0003` validator according to the current directory structure of `AMO`.

Refactoring AM0003 code according to the current directory structure.

---

internal/testdata/validators/am0015/csv_invalid_cpu_requirement.yaml
internal/testdata/validators/am0015/csv_invalid_livenessprobe.yaml
internal/testdata/validators/am0015/csv_invalid_memory_requirement.yaml
internal/testdata/validators/am0015/csv_invalid_readinessprobe.yaml
internal/testdata/validators/am0015/csv_valid.yaml
pkg/validator/am0015/csv_deployments.go
pkg/validator/am0015/csv_deployments_test.go
pkg/validator/register/register.go

A new validator for CSV deployments:
* All deployments defined in the CSV must have resources requests and limits defined for both CPU and Memory.
* All deployments defined in the CSV must have readiness and liveness probe defined.

[MTSRE-602] AMO: Validator for CSV deployments

---

cmd/mtcli/validate/cmd.go

Ensure the default OCM client uses the correct API URL during validation.

fix: ensure ocm client uses correct url during validation

---

.github/dependabot.yml

Adds dependabot config for dev dependencies.

chore: add dependabot for dev-deps

---

api/v1alpha1/addonmetadata_types.go

fix: remove display-name regex

---

integration/mtcli/test_harness_test.go
internal/testdata/metadata_v1/legacy/connectors-operator/metadata/stage/addon.yaml

AM0005 enabled integration test

feat: AM0005 enabled integration test

---

pkg/validator/am0016/additional_catalog_source.go
pkg/validator/am0016/additional_catalog_source_test.go
pkg/validator/register/register.go

A new validator ensuring additional catalog source names are unique.

[MTSRE-729] AM0016 validator ensuring additional catalog source are unique

---

pkg/validator/am0017/secret.go
pkg/validator/am0017/secret_test.go
pkg/validator/register/register.go

[MTSRE-731] AM0017: Secret names must be unique

---

api/v1alpha1/addonimageset_types.go

Updating imageset api according to the latest imageset schema.
Ref: https://github.com/mt-sre/managed-tenants-cli/blob/main/managedtenants/schemas/imageset.schema.yaml#L14

Adding PackageImage to imageset api

---

api/v1alpha1/addonmetadata_types.go
pkg/mtsre/v1/addons.go

Updating AMO API to keep in sync with mt-cli schemas

feat: AMO API parity with mt-cli schemas

---

Dockerfile.release

fix: bump goreleaser image version
