internal/cmd/list_bundles.go, internal/cmd/validate.go, pkg/utils/bundle_utils.go, pkg/utils/default_index_image_extractor.go
This PR adds a new subcommand `list-bundles` to list the operator bundles present in an index image
=> list-bundles subcommand

Dockerfile.build, Dockerfile.ci
The image we were using is now private and can't be pulled.
This is a fix. Tested both `pr_check.sh` and `build_tag.sh` locally.
=> Change CI docker image.

integration/mtcli/list_bundles_test.go, internal/cmd/list_bundles.go
This PR changes how operator names are constructed from a parsed bundle. Earlier, we were constructing the name from the package name + version. Turns out this is not ideal as some operators can have different package name compared to the name in the CSV.
Signed-off-by: ashish <asnaraya@redhat.com>
=> change how operator name is constructed from a parsed bundle

Makefile, internal/cmd/validate.go, pkg/validate/validate.go, pkg/validate/validate_test.go
This is necessary and provides more flexibility when integrating with the managed-tenants pipeline.
We are currently facing an issue where validators are not passing checks, and this is a blocker. As we work on fixing those validators, we can temporarily disable them and keep working on new validators, as well as fixing older ones.
Will also be useful if we ever introduce a bug and somehow need to quickly pass the pipeline.
=> Add a --disable/--enabled flag to validate cmd.

Makefile
Required to exit early on CI errors.
=> Fix make early exit.

internal/testutils/testutils.go, internal/testutils/testutils_test.go
Removing a `log.Fatal(...)` that gets executed at every runtime since the `RootDir` var is initialized.
Moving the validation to a test should fix the current build error:
```bash
$ /tmp/mtcli-0.7.0 version
2022/01/03 10:58:39 can't read root directory, got: open /addon-metadata-operator: no such file or directory
exit 1
```
=> Fix broken build error.

go.mod, go.sum, internal/cmd/validate.go, pkg/validate/print.go, pkg/validate/validate.go, pkg/validators/am0002_addon_label.go
Using new fields in the Validator struct to provide better validation output.
Advertise the new wiki: https://github.com/mt-sre/addon-metadata-operator/wiki/<code>
Fix output breaking with inconsistent tabs.
Example of new output:
```bash
$ go run cmd/mtcli/main.go validate ../managed-tenants/addons/reference-addon
```
=> New output formatting for ValidateCLI.

pkg/utils/bundle_utils.go
Metadata will include a placeholder value for indexImage during on-boarding which is unpullable. This PR includes a guard to bypass image pull and bundle loading in this scenario.
=> [MTSRE-397] adding bypass for tagless images required during on-boarding

pkg/validators/registry.go, pkg/validators/registry_test.go
~~Following a thread in addon-operator: https://github.com/openshift/addon-operator/pull/125#discussion_r781984425~~
~~We should pass mutex by value.~~
Edit: no need for registry to be concurrent safe.
=> Registry does not need to be concurrent safe.

internal/testutils/reference_addon.go, internal/testutils/testutils.go, internal/testutils/testutils_test.go, pkg/validators/am0007_test.go
Replacing public package vars in `testutils` package with public functions. Also eliminating relative path reference in `am0007_test.go`.
[Background](https://dave.cheney.net/2017/06/11/go-without-package-scoped-variables) on the dangers of global state in golang.
=> [MTSRE-399] Eliminating public package vars in 'testutils'

internal/cmd/list_validators.go, pkg/types/validators.go, pkg/types/validators_test.go, pkg/validators/registry.go, pkg/validators/registry_test.go
This will be useful to compare different releases of `mtcli`, and understand what validators are available.
```bash
$ go run cmd/mtcli/main.go list-validators
CODE            NAME                                            DESCRIPTION
-------- ----------------------- ------------------------------------------------------------------------------
AM0001   default_channel         Ensure defaultChannel is present in list of channels
AM0002   label_format            Validates whether label follows the format 'api.openshift.com/addon-<id>'
AM0004   icon_base64             Ensure that `icon` in Addon metadata is rightfully base64 encoded
AM0005   test_harness            Ensure that an addon has a valid testharness image
AM0006   dms_snitchnamepostfix   Ensure `deadmanssnitch.snitchNamePostFix` …
```
=> [MTSRE-395] mtcli list-validators

.goreleaser.yml, Makefile, pkg/extractor/index.go, pkg/extractor/index_cache.go, pkg/extractor/index_test.go, pkg/extractor/models.go
To be merged after #45 as it relies on types being in their own package.
An interesting thing is that we need to add `export CGO_CFLAGS="-DSQLITE_ENABLE_JSON1"` as otherwise `go-sqlite3` is built without the JSON extension, and we get cryptic errors when working with sql-based catalog:
```bash
populate channels: no such function: json_object
```
=> [MTSRE-384] IndexExtractor for both sql-based and file-based catalog

api/v1alpha1/addonmetadata_types.go, pkg/validators/am0007_csv_install_modes.go
Update AM0007 to also validate the installMode type in the metadata. This check ensures that the metadata only supports AllNamespaces and OwnNamespace install mode now that SingleNamespace has been completely dropped from managed-tenants.
=> AM0007: Validate installMode type in metadata

api/v1alpha1/addonmetadata_types.go, internal/kube/validation.go, pkg/mtsre/v1/addons.go, pkg/types/validators.go, pkg/validate/print.go, pkg/validate/validate.go, pkg/validators/am0010_k8s_resource_names.go, pkg/validators/am0010_test.go, pkg/validators/result.go
Several items are addressed in this PR as a follow up to #55:
- Additional k8s resource names were identified in the metadata (`pagerDuty.Secret`, `pagerDuty.SecretNameSpace` and `bundleParameters.AddonParamsSecretname`) and have been added to the scope of AM0010.
- Private helpers of AM0010 have been refactored and repackaged into more appropriate locations.
- The `validate` subcommand has also been enabled to write multiple failures for a single `ValidatorResult`.
=> Extending AM0010 to handle pagerDuty and bundleParameter fields with refactor

api/v1alpha1/addonmetadata_types.go, config/crd/bases/addons.managed.openshift.io_addonmetadata.yaml
Signed-off-by: Yashvardhan Kukreja <ykukreja@redhat.com>
Context: https://coreos.slack.com/archives/C01L46M0FQC/p1645434725467259?thread_ts=1645431585.151349&cid=C01L46M0FQC
=> allow displayName's regex to be able to comply with OperatorHub's style of defining [DEPRECATED] addons

go.mod, pkg/types/csv_rbac.go, pkg/types/csv_rbac_test.go, pkg/utils/csvutils/csv_rbac_utils.go, pkg/utils/csvutils/csv_rbac_utils_test.go, pkg/validators/am0012_csv_rbac.go, pkg/validators/am0012_test.go
This validator validates the rbac rules specified in the CSV file.
The validator currently runs the validations listed here: https://issues.redhat.com/browse/MTSRE-368.
I haven't enabled this validator yet, as this validation currently fails for many addons we handle currently.
=> Csv rbac validations

build_tag.sh
the goreleaser-cross image is coming from ghcr.io and not dockerhub https://github.com/goreleaser/goreleaser-cross/pkgs/container/goreleaser-cross it should work. In the meantime, i will create a mirror for this image
=> full docker path for goreleaser-cross image

.goreleaser.yml
small change from macOS to use Darwin as a system
=> release binary name for Mac: Darwin and not macOS

api/v1alpha1/addonmetadata_types.go, config/crd/bases/addons.managed.openshift.io_addonmetadata.yaml
Increases the validation length for `operatorName` beyond 32 characters.
=> [MTSRE-472] Extending operatorName valid length

pkg/validators/am0012_csv_rbac.go
Signed-off-by: ashish <asnaraya@redhat.com>
Enable AM0012 validator
=> enable am0012 validator

internal/testutils/ocm_mock.go, pkg/utils/default_ocm_client.go, pkg/validators/am0011_sku_validation.go, pkg/validators/am0011_test.go, pkg/validators/ocm_client.go
Using the `QuotaRules` endpoint to permit validation of addons with zero `ocmQuotaCost` defined.
=> [MTSRE-287] Updating from SkuRules endpoint to QuotaRules

.goreleaser.yml, Dockerfile.release, Makefile, build_tag.sh
- Removes root permissions from `build_tag.sh`
- Removes dependency on host volume when publishing release artifacts
- Moves release logic to `Makefile`
=> Removing root permissions from build_tag.sh

pkg/validator/am0013/addon_requirements.go, pkg/validator/am0013/addon_requirements_test.go, pkg/validator/register/register.go
Validates `addonRequirements` in particular that they contain non-empty data.
=> [MTSRE-502] AM0013 validator for addon requirements

magefile.go
Fixes docker build tag failure.
=> ci: fixing docker build tagging

cmd/mtcli/validate/cmd.go, pkg/validator/ocm_client.go
A couple of minor fixes to avoid overloaded error output when `mtcli validate` encounters a failure or error.
=> Ensure concise output from `mtcli validate`

pkg/validator/am0003/operator_name.go
Semver can be tolerant of `v` pre-fixed versions in `.metadata.name` and `.spec.replaces` as OPM does not correlate `.spec.version` with these values.
=> fix: make AM0003 tolerant of 'v' pre-fixed semver

internal/kube/lint.go, internal/kube/lint_test.go
Adds a linter for K8s deployments. Hopefully this is a temporary implementation until `kube-linter` import conflicts can be resolved.
=> feat: adding new deployment linter

pkg/validator/am0012/csv_rbac.go, pkg/validator/latest_bundle.go
Refactoring `getLatestBundle` function so that it can be used by other validators to validate on the latest bundles.
=> fix: code refactor for latest bundle

pkg/validator/am0001/default_channel.go, pkg/validator/am0001/default_channel_test.go
Added validation for annotations for validators AM0001 (AM0003 is already covered in PR #111).
=> [MTSRE-390] AMO: validate annotations on AM0001 and AM0003

api/v1alpha1/addonmetadata_types.go
Deprecating `pullSecret` from AMO API.
=> fix: deprecating pullSecret from AMO API

pkg/validator/am0018/pull_secret_name.go, pkg/validator/am0018/pull_secret_name_test.go, pkg/validator/register/register.go
Addon pullSecretName is the name of the secret under `secrets` which is supposed to be used for pulling Catalog Image under CatalogSource. As of now, there is no check to validate if pullSecretName is not nil, it is a part of secrets. 
This validator ensures the same.
=> [MTSRE-741] AM0018 Addon pullSecretName should be a part of secrets.

Dockerfile.release
Bumps goreleaser-cross image to go 1.19
=> ci: use goreleaser 1.19 image

.github/dependabot.yml
Adding automatic `ok-to-test` label for dependency updates
=> feat: adding automatic ok-to-test label for dependency updates
